/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MAli
 */

import javax.swing.*;

public class loginScreen extends javax.swing.JFrame {

    /**
     * Creates new form loginScreen
     */
    String s1;
    String s2;
    public loginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        passFeild = new javax.swing.JPasswordField();
        showPass = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(153, 204, 255));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\MAli\\OneDrive - Higher Education Commission\\Documents\\loginScreen.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-71, 0, 720, 720);

        jLabel3.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel3.setText("Sign In");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(710, 100, 97, 35);

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel4.setText("USERNAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(710, 160, 100, 15);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel5.setText("PASSWORD");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(710, 240, 100, 15);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(710, 180, 210, 40);

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(710, 370, 210, 40);

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(650, 10, 72, 27);

        passFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFeildActionPerformed(evt);
            }
        });
        getContentPane().add(passFeild);
        passFeild.setBounds(710, 270, 210, 40);

        showPass.setText("Show Password");
        showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassActionPerformed(evt);
            }
        });
        getContentPane().add(showPass);
        showPass.setBounds(710, 320, 120, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String s1 = jTextField1.getText();
            char[] passChar = passFeild.getPassword();
            String s2 = new String(passChar);
      
            if (evt.getActionCommand().equals("Sign In")) {
                if(SBS.verifyManagerLogin(s1, s2)){
                     dispose();
                        Manager m2 = new Manager();
                        m2.setVisible(true);

                }else if (SBS.verifyCashierLogin(s1, s2)) {
                    dispose();
                        AddToCart  at = new AddToCart();
                        at.setVisible(true);

                } else {
                        JOptionPane.showMessageDialog(new JFrame(), "Incorrect Username or Password");
                        //dispose();
                       // loginScreen l = new loginScreen();

                    
                }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
         // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HomeScreen h2 = new HomeScreen();
        h2.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void passFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFeildActionPerformed

    private void showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassActionPerformed
               JCheckBox checkBox = (JCheckBox) evt.getSource();
                if (checkBox.isSelected()) {
                    passFeild.setEchoChar((char) 0); // Show password as plain text
                } else {
                    passFeild.setEchoChar('\u2022'); // Hide password
                }
    }//GEN-LAST:event_showPassActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField passFeild;
    private javax.swing.JCheckBox showPass;
    // End of variables declaration//GEN-END:variables
}
